// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnwvnlgspaxuzbfiphik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJud3ZubGdzcGF4dXpiZmlwaGlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NDQ5ODAsImV4cCI6MjA2MjEyMDk4MH0.T9JJPTYvFrH9YXr55loiC5f3tx19WtH_Rtr6BpNNkJU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);